Weather/Controllers/ViewWeatherController.cs
using Microsoft.AspNetCore.Mvc;
using Weather.Models;
using Weather.Repository.Contracts;

namespace Weather.Controllers
{
    public class ViewWeatherController : Controller
    {
        private readonly IWeatherRepository weatherRepository;

        public ViewWeatherController(IWeatherRepository weatherRepository)
        {
            this.weatherRepository = weatherRepository;
        }

        /// <summary>
        /// Отображение погоды.
        /// </summary>
        /// <param name="year">Фильтр по году.</param>
        /// <param name="month">Фильтр по месяцу.</param>
        /// <param name="currentPage">Текущая страница.</param>
        /// <param name="pageSize">Кол-во элементов на странице.</param>
        /// <returns></returns>
        public async Task<IActionResult> ViewWeather(int year = 0, int month = 0, int currentPage = 1, int pageSize = 10)
        {
            // Полчаем погоду с учетом фильтров.
            var weathers = await weatherRepository.GetWeatherForFilters(year, month);

            // Собираем View модель для отображения.
            var groupedWeathers = weathers.GroupBy(w => w.DateTime.Date)
                .Select(g => new WeatherViewModel
                {
                    Date = g.Key,
                    Weathers = g.OrderBy(w => w.DateTime.TimeOfDay)
                    .ToList()
                })
                .OrderBy(w => w.Date).ToList();

            // Пагинация.
            var count = groupedWeathers.Count();
            var items = groupedWeathers.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();
            var totalPages = (int)Math.Ceiling(count / (double)pageSize);

            ViewData["CurrentPage"] = currentPage;
            ViewData["PageSize"] = pageSize;
            ViewData["TotalPages"] = totalPages;
            ViewData["Year"] = year;
            ViewData["Month"] = month;

            return View(items);
        }
    }
}

Weather/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Weather</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Weather.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Weather</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewWeather" asp-action="ViewWeather">Просмотр погоды</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoadingWeather" asp-action="LoadingWeather">Загрузка погоды</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>